import { Crimson_Pro } from 'next/font/google'
import localFont from 'next/font/local'

import './global.css'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

const crimson = Crimson_Pro({
  weight: ['200', '900'],
  style: ['italic', 'normal'],
  display: 'fallback',
  subsets: ['latin'],
  variable: '--font-crimson'
})

const chomsky = localFont({
  src: './fonts/chomsky.woff2',
  style: 'normal',
  weight: '700',
  display: 'block',
  variable: '--font-chomsky'
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`${crimson.variable} ${chomsky.variable}`}>
      <body>{children}</body>
    </html>
  )
}
